const translations = {
  en: {
    site_title: "PUBG Arena",
    home: "Home",
    tournaments: "Tournaments",
    login: "Login",
    signup: "Sign Up",
    profile: "Profile",
    admin: "Admin",
    logout: "Logout",

    hero_tag: "COMPETITIVE PUBG TOURNAMENTS",
    hero_title: "ENTER THE BATTLEGROUND",
    hero_text: "Join custom PUBG tournaments, build your profile, compete with real players, and rise through the leaderboard.",
    join_tournament: "Join a Tournament",
    create_account: "Create Account",

    why_join: "Why Players Join",
    why_join_text: "Everything needed for a strong PUBG community",
    feature_1_title: "Custom Tournaments",
    feature_1_text: "Solo, duo, and squad events with organized registration and clear match flow.",
    feature_2_title: "Fast Approvals",
    feature_2_text: "Players request entry and the admin can approve them before matches begin.",
    feature_3_title: "Competitive Community",
    feature_3_text: "Build a serious player base, reward activity, and make your platform stand out.",

    ready_label: "READY TO PLAY?",
    highlight_title: "Build your reputation in every match",
    highlight_text: "Whether you play solo, duo, or squad, PUBG Arena helps you find events and compete in organized rooms.",
    highlight_1: "Live room access",
    highlight_2: "Approval-based entry",
    highlight_3: "Fast tournament browsing",

    footer_text: "Built for competitive players.",

    stat_tournaments: "Tournaments",
    stat_players: "Players",
    stat_rooms: "Custom Rooms",

    email_placeholder: "Email",
    password_placeholder: "Password",
    login: "Login",

    signup: "Sign Up",
    username_placeholder: "Username",
    email_placeholder: "Email",
    password_placeholder: "Password",
    pubg_uid_placeholder: "PUBG UID",
    discord_placeholder: "Discord username",

    room_access: "Room Access",
    available_tournaments: "Available Tournaments",
    request_sent: "Request Sent",
    joined: "Joined",
    full: "Full",
    login_required: "Login Required",
    join_tournament: "Join Tournament",
    must_login_first: "You must login first",
    room_id: "Room ID",
    room_password: "Room Password",
    not_set_yet: "Not set yet",
    mode: "Mode",
    prize: "Prize",
    date: "Date",
    status: "Status",
    players: "Players",
    waiting: "Waiting",
    open: "Open",
    live: "Live",
    finished: "Finished",
    room_access_live: "Available only to approved players when match is Live"
  },

  ru: {
    site_title: "PUBG Arena",
    home: "Главная",
    tournaments: "Турниры",
    login: "Войти",
    signup: "Регистрация",
    profile: "Профиль",
    admin: "Админ",
    logout: "Выйти",

    hero_tag: "СОРЕВНОВАТЕЛЬНЫЕ PUBG ТУРНИРЫ",
    hero_title: "ВОЙДИ НА ПОЛЕ БОЯ",
    hero_text: "Участвуйте в пользовательских турнирах PUBG, создавайте профиль, соревнуйтесь с реальными игроками и поднимайтесь выше.",
    join_tournament: "Присоединиться",
    create_account: "Создать аккаунт",

    why_join: "Почему игроки выбирают нас",
    why_join_text: "Все необходимое для сильного PUBG сообщества",
    feature_1_title: "Пользовательские турниры",
    feature_1_text: "Соло, дуо и сквад турниры с организованной регистрацией и понятным процессом матчей.",
    feature_2_title: "Быстрое одобрение",
    feature_2_text: "Игроки отправляют запрос, а админ подтверждает участие перед началом матча.",
    feature_3_title: "Сильное сообщество",
    feature_3_text: "Создавайте серьезную базу игроков, поощряйте активность и развивайте платформу.",

    ready_label: "ГОТОВ ИГРАТЬ?",
    highlight_title: "Создавай свою репутацию в каждом матче",
    highlight_text: "Играете ли вы соло, дуо или сквадом — PUBG Arena помогает находить турниры и участвовать в организованных комнатах.",
    highlight_1: "Доступ к комнате во время Live",
    highlight_2: "Вход по одобрению",
    highlight_3: "Быстрый поиск турниров",

    footer_text: "Создано для соревновательных игроков.",

    stat_tournaments: "Турниры",
    stat_players: "Игроки",
    stat_rooms: "Комнаты",

    email_placeholder: "Email",
    password_placeholder: "Пароль",
    login: "Войти",

    signup: "Регистрация",
    username_placeholder: "Имя пользователя",
    email_placeholder: "Email",
    password_placeholder: "Пароль",
    pubg_uid_placeholder: "PUBG UID",
    discord_placeholder: "Имя в Discord",

    room_access: "Доступ к комнате",
    available_tournaments: "Доступные турниры",
    request_sent: "Запрос отправлен",
    joined: "Вы участвуете",
    full: "Заполнено",
    login_required: "Нужен вход",
    join_tournament: "Присоединиться",
    must_login_first: "Сначала войдите",
    room_id: "ID комнаты",
    room_password: "Пароль комнаты",
    not_set_yet: "Еще не задано",
    mode: "Режим",
    prize: "Приз",
    date: "Дата",
    status: "Статус",
    players: "Игроки",
    waiting: "Ожидание",
    open: "Открыто",
    live: "Идет матч",
    finished: "Завершено",
    room_access_live: "Доступно только одобренным игрокам, когда матч Live"
  },

  uz: {
    site_title: "PUBG Arena",
    home: "Bosh sahifa",
    tournaments: "Turnirlar",
    login: "Kirish",
    signup: "Ro'yxatdan o'tish",
    profile: "Profil",
    admin: "Admin",
    logout: "Chiqish",

    hero_tag: "RAQOBATBARDOSH PUBG TURNIRLARI",
    hero_title: "JANG MAYDONIGA KIRING",
    hero_text: "Maxsus PUBG turnirlariga qo‘shiling, profilingizni yarating, haqiqiy o‘yinchilar bilan raqobatlashing va yuqoriga ko‘tariling.",
    join_tournament: "Turnirga qo‘shilish",
    create_account: "Hisob yaratish",

    why_join: "Nega o'yinchilar qo‘shiladi",
    why_join_text: "Kuchli PUBG hamjamiyati uchun kerak bo‘ladigan hamma narsa",
    feature_1_title: "Maxsus turnirlar",
    feature_1_text: "Aniq tizim bilan solo, duo va squad turnirlari.",
    feature_2_title: "Tez tasdiqlash",
    feature_2_text: "O‘yinchilar so‘rov yuboradi va admin match boshlanishidan oldin tasdiqlaydi.",
    feature_3_title: "Kuchli hamjamiyat",
    feature_3_text: "Jiddiy o‘yinchilar bazasini yarating, faollikni oshiring va platformangizni rivojlantiring.",

    ready_label: "O‘YNASHGA TAYYORMISIZ?",
    highlight_title: "Har bir matchda obro‘yingizni oshiring",
    highlight_text: "Solo, duo yoki squad bo‘lishidan qat’i nazar, PUBG Arena sizga turnir topish va tartibli xonalarda qatnashishga yordam beradi.",
    highlight_1: "Live paytda xona ko‘rinadi",
    highlight_2: "Tasdiq orqali kirish",
    highlight_3: "Turnirlarni tez ko‘rish",

    footer_text: "Raqobatbardosh o‘yinchilar uchun qurilgan.",

    stat_tournaments: "Turnirlar",
    stat_players: "O'yinchilar",
    stat_rooms: "Maxsus xonalar",

    email_placeholder: "Email",
    password_placeholder: "Parol",
    login: "Kirish",

    signup: "Ro'yxatdan o'tish",
    username_placeholder: "Foydalanuvchi nomi",
    email_placeholder: "Email",
    password_placeholder: "Parol",
    pubg_uid_placeholder: "PUBG UID",
    discord_placeholder: "Discord nomi",

    room_access: "Xona ma'lumotlari",
    available_tournaments: "Mavjud turnirlar",
    request_sent: "So'rov yuborildi",
    joined: "Qo'shilgansiz",
    full: "To'lgan",
    login_required: "Avval kiring",
    join_tournament: "Turnirga qo'shilish",
    must_login_first: "Avval tizimga kiring",
    room_id: "Xona ID",
    room_password: "Xona paroli",
    not_set_yet: "Hali kiritilmagan",
    mode: "Rejim",
    prize: "Sovrin",
    date: "Sana",
    status: "Holat",
    players: "O'yinchilar",
    waiting: "Kutilmoqda",
    open: "Ochiq",
    live: "Jonli",
    finished: "Tugagan",
    room_access_live: "Faqat tasdiqlangan o'yinchilarga match Live bo'lganda ko'rinadi"
  }
};